package com.lh.cd.entity.mapper;

import com.lh.cd.entity.model.TabfDistrict;
import com.lh.cd.entity.model.TabfDistrictExample;
import com.lh.cd.pub.db.SqlMapper;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TabfDistrictMapper extends SqlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabf_district
     *
     * @mbggenerated
     */
    int countByExample(TabfDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabf_district
     *
     * @mbggenerated
     */
    int deleteByExample(TabfDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabf_district
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabf_district
     *
     * @mbggenerated
     */
    int insert(TabfDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabf_district
     *
     * @mbggenerated
     */
    int insertSelective(TabfDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabf_district
     *
     * @mbggenerated
     */
    List<TabfDistrict> selectByExample(TabfDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabf_district
     *
     * @mbggenerated
     */
    TabfDistrict selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabf_district
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TabfDistrict record, @Param("example") TabfDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabf_district
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TabfDistrict record, @Param("example") TabfDistrictExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabf_district
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TabfDistrict record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tabf_district
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TabfDistrict record);
}