package com.lh.cd.entity.mapper;

import com.lh.cd.entity.model.TabSysRole;
import com.lh.cd.entity.model.TabSysRoleExample;
import com.lh.cd.pub.db.SqlMapper;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TabSysRoleMapper extends SqlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_sys_role
     *
     * @mbggenerated
     */
    int countByExample(TabSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_sys_role
     *
     * @mbggenerated
     */
    int deleteByExample(TabSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_sys_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_sys_role
     *
     * @mbggenerated
     */
    int insert(TabSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_sys_role
     *
     * @mbggenerated
     */
    int insertSelective(TabSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_sys_role
     *
     * @mbggenerated
     */
    List<TabSysRole> selectByExample(TabSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_sys_role
     *
     * @mbggenerated
     */
    TabSysRole selectByPrimaryKey(Integer roleId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_sys_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TabSysRole record, @Param("example") TabSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_sys_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TabSysRole record, @Param("example") TabSysRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_sys_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TabSysRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_sys_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TabSysRole record);
}