package com.lh.cd.entity.mapper;

import com.lh.cd.entity.model.TabSysMenuFile;
import com.lh.cd.entity.model.TabSysMenuFileExample;
import com.lh.cd.pub.db.SqlMapper;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TabSysMenuFileMapper extends SqlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_sys_menu_file
     *
     * @mbggenerated
     */
    int countByExample(TabSysMenuFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_sys_menu_file
     *
     * @mbggenerated
     */
    int deleteByExample(TabSysMenuFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_sys_menu_file
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_sys_menu_file
     *
     * @mbggenerated
     */
    int insert(TabSysMenuFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_sys_menu_file
     *
     * @mbggenerated
     */
    int insertSelective(TabSysMenuFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_sys_menu_file
     *
     * @mbggenerated
     */
    List<TabSysMenuFile> selectByExample(TabSysMenuFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_sys_menu_file
     *
     * @mbggenerated
     */
    TabSysMenuFile selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_sys_menu_file
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TabSysMenuFile record, @Param("example") TabSysMenuFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_sys_menu_file
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TabSysMenuFile record, @Param("example") TabSysMenuFileExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_sys_menu_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TabSysMenuFile record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_sys_menu_file
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TabSysMenuFile record);
}