package com.lh.cd.entity.mapper;

import com.lh.cd.entity.model.TabUserAuth;
import com.lh.cd.entity.model.TabUserAuthExample;
import com.lh.cd.pub.db.SqlMapper;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TabUserAuthMapper extends SqlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_auth
     *
     * @mbggenerated
     */
    int countByExample(TabUserAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_auth
     *
     * @mbggenerated
     */
    int deleteByExample(TabUserAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_auth
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_auth
     *
     * @mbggenerated
     */
    int insert(TabUserAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_auth
     *
     * @mbggenerated
     */
    int insertSelective(TabUserAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_auth
     *
     * @mbggenerated
     */
    List<TabUserAuth> selectByExample(TabUserAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_auth
     *
     * @mbggenerated
     */
    TabUserAuth selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_auth
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TabUserAuth record, @Param("example") TabUserAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_auth
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TabUserAuth record, @Param("example") TabUserAuthExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_auth
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TabUserAuth record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_auth
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TabUserAuth record);
}