package com.lh.cd.entity.mapper;

import com.lh.cd.entity.model.TabUserRole;
import com.lh.cd.entity.model.TabUserRoleExample;
import com.lh.cd.pub.db.SqlMapper;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface TabUserRoleMapper extends SqlMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_role
     *
     * @mbggenerated
     */
    int countByExample(TabUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_role
     *
     * @mbggenerated
     */
    int deleteByExample(TabUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_role
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_role
     *
     * @mbggenerated
     */
    int insert(TabUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_role
     *
     * @mbggenerated
     */
    int insertSelective(TabUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_role
     *
     * @mbggenerated
     */
    List<TabUserRole> selectByExample(TabUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_role
     *
     * @mbggenerated
     */
    TabUserRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_role
     *
     * @mbggenerated
     */
    int updateByExampleSelective(@Param("record") TabUserRole record, @Param("example") TabUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_role
     *
     * @mbggenerated
     */
    int updateByExample(@Param("record") TabUserRole record, @Param("example") TabUserRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(TabUserRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table tab_user_role
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(TabUserRole record);
}